name: CI Testing

on: [push, pull_request]

jobs:
  pytest_job:
    timeout-minutes: 60

    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set-up Python dependences
        run: |
          pip3 install -e .        # from setup.py
          pip3 install matplotlib  # extra packages
          pip3 install pytest      # testing packages

      - name: Run functional tests
        run: python3 -m pytest tests/test_scritpts.py -vv